SELECT ?property ?propertyLabel ?value WHERE {    
  ?property wikibase:propertyType wikibase:ExternalId .    
  ?property wikibase:directClaim ?propertyclaim . 
  wd:Q30347498 ?propertyclaim ?value .   
  ?property rdfs:label ?propertyLabel .
  FILTER (lang(?propertyLabel)= "en") . 
}
