SELECT DISTINCT ?item ?itemLabel WHERE {
   ?item ?p ?statement.
   ?statement prov:wasDerivedFrom ?ref . 
   ?ref ?prop wd:Q28061352 .
   OPTIONAL { ?item rdfs:label ?itemLabel .
              FILTER (lang(?itemLabel) = "en" ) }
}
